ENG-1724 - Create generic tokens with elements
Basis-Theory/docs pull request #119
Opened 2021-11-24 14:22 UTC by lcschy

## Description

- Adds docs for creating generic tokens with elements

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/9054729/143255714-ee548eba-4579-4019-84c7-d296ebe690e3.png)

- [x] Not Applicable

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2021-11-24 15:41 UTC, djejaquino requested changes

2021-11-24 15:41 UTC, djejaquino commented on source/includes/elements/_elements_services.md
> +    sensitiveData: sensitiveDataElement | 'plainText',  // values can be either a TextElement or plain text (see warning).
Can we enhance this with more elements in different formats, so users know they are free to use multiple elements within an arbitrary payload?

2021-11-24 22:03 UTC, armsteadj1 requested changes

2021-11-24 22:03 UTC, armsteadj1 commented on source/includes/elements/_elements_services.md
> +Allows secure submission and tokenization of generic data. Returns a `Promise` that resolves to the created token.
```suggestion
Allows secure submission and tokenization of string data. Returns a `Promise` that resolves to the created token.
```

2021-11-25 12:36 UTC, djejaquino approved these changes

2021-11-25 12:37 UTC, merged

2021-11-25 12:38 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/docs/releases/tag/v1.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: