ENG 1793 - Adds proxy docs
Basis-Theory/docs pull request #130
Opened 2021-12-06 20:52 UTC by dhudec

## Description

- Adds section for proxy to the docs

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/1900725/144920612-b871261a-bfbb-47a9-a87e-d8db1be8484a.png)

![image](https://user-images.githubusercontent.com/1900725/144920697-ed5d8a9e-02fd-4d58-87fc-b74825df551d.png)

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2021-12-06 21:17 UTC, koalaty-code commented on source/includes/api-reference/_proxy.md
> +  <span>The Basis Theory Proxy is currently available publicly but is still in beta status. The features listed below are subject to change. If you are interested in using the proxy and your use case
"The Basis Theory Proxy is currently available in Public Beta" instead of publicly but in beta status?

2021-12-06 21:17 UTC, koalaty-code commented on source/includes/api-reference/_proxy.md
> +The Basis Theory Proxy provides a simple mechanism to use your token data stored in the Basis Theory Vault in outbound requests to a third party API.
Should the action verb talking about proxy be "use", "share", or "enrich"? We should try to be consistent with whatever we choose and try to use the same verbiage with our product categories.

2021-12-06 21:17 UTC, koalaty-code commented on source/includes/api-reference/_proxy.md
> +Requests containing tokens can be sent to a third party through the proxy and Basis Theory will detect the presence of these tokens and substitute the raw token data within the request that is forwar
```suggestion
Requests containing [token interpolation patterns](#link-to-interpolation-patterns) can be sent to a third party through the Proxy. The interpolation patterns will be replaced with the raw token data and then the request will be forwarded to the destination specified in the `BT-PROXY-URL` request header. The destination will receive the detokenized data in the request without your system needing to interact with this sensitive data on your own servers.
```

2021-12-06 21:17 UTC, koalaty-code commented on source/includes/api-reference/_proxy.md
> +Proxy requests require a `BT-PROXY-URL` header to be included. The value of this header defines the destination url to which the request will be proxied.
```suggestion
Proxy requests require a `BT-PROXY-URL` request header to be set. The value of `BT-PROXY-URL` header defines the base URL to which the request will be proxied.
```

2021-12-06 21:17 UTC, koalaty-code commented on source/includes/api-reference/_proxy.md
> +We require that the destination url uses HTTPS with >= TLSv1.2 on port 443. The url must specify the url using DNS - direct IP addresses are not supported.
```suggestion
The `BT-PROXY-URL` request header must use HTTPS with DNS as the host. Destinations must use HTTPS  >= TLSv1.2 over port 443.
```

2021-12-06 21:17 UTC, koalaty-code commented on source/includes/api-reference/_proxy.md
> +The `BT-PROXY-URL` header and the `/proxy` endpoint both support urls that include routes or query string parameters and these values will be included in the proxied request.
```suggestion
The `BT-PROXY-URL` request header will serve as the base URL for the proxied request. Any path and/or query parameters under `/proxy/**` will be appended to the base URL before forwarding the request. 
```

2021-12-06 21:17 UTC, koalaty-code commented on source/includes/api-reference/_proxy.md
> +then the following request body will sent to the desintation url:
```suggestion
then the following request body will sent to the desintation:
```

2021-12-06 21:40 UTC, armsteadj1 requested changes

2021-12-06 21:40 UTC, armsteadj1 commented on source/includes/api-reference/_proxy.md
> +The Basis Theory Proxy provides a simple mechanism to use your token data stored in the Basis Theory Vault in outbound requests to a third party API.
```suggestion
The Basis Theory Proxy provides a simple mechanism to use the data you've stored with Basis Theory in outbound requests to a third party API.
```

2021-12-06 21:40 UTC, armsteadj1 commented on source/includes/api-reference/_proxy.md
> +Requests containing tokens can be sent to a third party through the proxy and Basis Theory will detect the presence of these tokens and substitute the raw token data within the request that is forwar
```suggestion
Requests containing Basis Theory Token identifiers sent to the Basis Theory Proxy will be substituted for the raw token data within the request that is forwarded to the third party API. The third party will receive the raw data in the request without your system needing to interact with this sensitive data on your own servers.
```

2021-12-06 21:40 UTC, armsteadj1 commented on source/includes/api-reference/_proxy.md
> +At least one of the following permissions is required:
```suggestion
Depending on the type of data you need to forward to a 3rd party, at least one of the following permissions is required:
```

2021-12-06 21:40 UTC, armsteadj1 commented on source/includes/api-reference/_proxy.md
> +Note that requests may contain a mixture of both token interpolation patterns and non-interpolated raw data. The `<token_type>:use` permission is required in order to detokenize tokens of type `<toke
```suggestion
Requests may contain a mixture of both token interpolation patterns and non-interpolated raw data. The `<token_type>:use` permission is required in order to detokenize tokens of type `<token_type>` within a proxy request. At most 100 unique tokens may be detokenized within a single proxy request.
```

2021-12-06 21:40 UTC, armsteadj1 commented on source/includes/api-reference/_proxy.md
> +Detokenization is the process of exchanging a non-sensitive token for the senstitive data that token represents. The Basis Theory Proxy will attempt to detokenize certain interpolation patterns in th
```suggestion
The Basis Theory Proxy will attempt to detokenize certain interpolation patterns and inject the raw token data in the request body before sending the request to the downstream destination.
```

2021-12-06 21:40 UTC, armsteadj1 commented on source/includes/api-reference/_proxy.md
> +given a token of the form:
```suggestion
given a token:
```

2021-12-06 21:40 UTC, armsteadj1 commented on source/includes/api-reference/_proxy.md
> +and a proxy request with a body of the form:
```suggestion
and a proxy request with a body of:
```

2021-12-06 23:12 UTC, jleon15 commented on source/includes/api-reference/_proxy.md
> +At least one of the following permissions is required:
Previously we used third party and here we use 3rd party, so let's be consistent with one or the other.

2021-12-07 15:18 UTC, armsteadj1 approved these changes

2021-12-07 15:26 UTC, merged

2021-12-07 18:36 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.16.1 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/docs/releases/tag/v1.16.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: