feat: Adds Detokenization reference docs and removes encryption docs
Basis-Theory/docs pull request #163
Opened 2022-03-31 21:35 UTC by dhudec

## Description

- Adds Detokenization reference docs section
- Removes all mentions of you encrypt
- Update API Reference sidebar to add a new Reference section to match developers.basistheory.com

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/1900725/161152084-d3e7269a-aabd-4c72-9493-4f69ad728071.png)

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-03-31 22:12 UTC, jleon15 commented on source/includes/detokenization/_intro.md
> +Basis Theory supports detokenization through our serverless [Reactor](#reactors) platform and the [Proxy](#proxy).
Clicking on reactors or proxy doesn't work as it adds the # under the detokenization path

2022-03-31 22:16 UTC, jleon15 commented on source/includes/detokenization/_intro.md
> +Basis Theory supports detokenization through our serverless [Reactor](#reactors) platform and the [Proxy](#proxy).
```suggestion
Basis Theory supports detokenization through our serverless [Reactor](/#reactors) platform and the [Proxy](/#proxy).
```

2022-03-31 22:16 UTC, jleon15 commented on source/includes/detokenization/_expressions.md
> +[Reactor](/#reactors-invoke-a-reactor) or [Proxy](/#permissions-proxying-outbound-requests).
For some reason the Proxy link redirects to the API Reference intro

2022-03-31 22:20 UTC, jleon15 commented on source/includes/detokenization/_expressions.md
> +Atomic Card or Bank tokens or generic tokens containing complex JSON objects can all be detokenized as well.
```suggestion
Atomic Card, Atomic Bank or generic tokens containing complex JSON objects can all be detokenized as well.
```

2022-03-31 22:21 UTC, jleon15 commented on source/includes/detokenization/_expressions.md
> +will be detokenized into the request:
```suggestion
which will be detokenized into the request:
```

2022-03-31 22:24 UTC, jleon15 commented on source/includes/detokenization/_transformations.md
> +You can effectively think of this as "piping" the token data into the transformation function in the same way you may be familiar with the "pipe" operator from Unix-like systems.
```suggestion
You can effectively think of this as "piping" the token data into the transformation function in the same way you might be familiar with the "pipe" operator from Unix-like systems.
```

2022-03-31 22:26 UTC, jleon15 commented on source/includes/detokenization/_transformations.md
> +JSON data, arbitrary [JSON Path](https://tools.ietf.org/id/draft-goessner-dispatch-jsonpath-00.html) expressions can be applied to a token's data:
I saw this in that site you linked: `This Internet-Draft will expire on 13 January 2021.` Does it mean anything?

2022-03-31 22:36 UTC, jleon15 commented on source/includes/detokenization/_transformations.md
> +| <code>{{d35412f4-9d3b-45d8-b051-fe4b7d4e14c5 &#124; $.book[(@.price < 10)]}}.title</code> | "Moby Dick"                        |
This is wrong, it is missing the ? and the .title should be inside the expression
```suggestion
| <code>{{d35412f4-9d3b-45d8-b051-fe4b7d4e14c5 &#124; $.book[?(@.price < 10)].title}}</code> | "Moby Dick"                        |
```

2022-03-31 22:37 UTC, jleon15 commented on source/includes/detokenization/_transformations.md
> +| <code>{{d35412f4-9d3b-45d8-b051-fe4b7d4e14c5 &#124; $.nonexistent</code>                  | `null`                             |
Missing }}
```suggestion
| <code>{{d35412f4-9d3b-45d8-b051-fe4b7d4e14c5 &#124; $.nonexistent}}</code>                  | `null`                             |
```

2022-03-31 22:39 UTC, jleon15 commented on source/includes/detokenization/_transformations.md
> +| <code>{{d35412f4-9d3b-45d8-b051-fe4b7d4e14c5 &#124; $.book..author</code>                 | <400 Error>                        |
Missing }}
```suggestion
| <code>{{d35412f4-9d3b-45d8-b051-fe4b7d4e14c5 &#124; $.book..author}}</code>                 | <400 Error>                        |
```

2022-03-31 22:43 UTC, jleon15 commented on source/includes/detokenization/_examples.md
> +If Reactors or Proxy are completely new to you, we recommend you first read our [Reactors](/concepts/what-are-reactors)
Both of these links return 404, these concepts are under https://developers.basistheory.com/
```suggestion
If Reactors or Proxy are completely new to you, we recommend you first read our [Reactors](https://developers.basistheory.com//concepts/what-are-reactors) 
```

2022-03-31 22:51 UTC, jleon15 commented on source/includes/detokenization/_examples.md
> +but provide an updated CVC (`987`) that is different from the `cvc` value stored with the token.
```suggestion
but provide an updated CVC (`987`) that is different from the `cvc` value stored within the token.
```

2022-03-31 22:56 UTC, jleon15 requested changes
Looks good, added some comments.

2022-04-01 14:11 UTC, dhudec commented on source/includes/detokenization/_transformations.md
> +You can effectively think of this as "piping" the token data into the transformation function in the same way you may be familiar with the "pipe" operator from Unix-like systems.
I think `may` sounds better here.

2022-04-01 14:20 UTC, dhudec commented on source/includes/detokenization/_transformations.md
> +JSON data, arbitrary [JSON Path](https://tools.ietf.org/id/draft-goessner-dispatch-jsonpath-00.html) expressions can be applied to a token's data:
I added a second link to another website. Idk what the date is, but that's the official proposed spec.

2022-04-01 14:34 UTC, dhudec commented on source/includes/detokenization/_transformations.md
> +| <code>{{d35412f4-9d3b-45d8-b051-fe4b7d4e14c5 &#124; $.nonexistent</code>                  | `null`                             |
I'm not sure what you mean... something like `"some text {{ ... }}"`? 

If so, that's an edge case I'm not too worried about explaining here, and it doesn't really fit with the other examples that don't show the context around the expression. Plus I'm already maxed on width in this table without pushing the results out of view.

2022-04-01 18:01 UTC, jleon15 submitted a review, later dismissed

2022-04-01 18:46 UTC, koalaty-code commented on source/includes/api-reference/_proxy.md
> +Proxy requests must be authenticated using an `BT-API-KEY` header (see [Authentication](#authentication)).
```suggestion
Proxy requests must be authenticated using a `BT-API-KEY` header (see [Authentication](#authentication)).
```

2022-04-01 18:46 UTC, koalaty-code commented on source/includes/detokenization/_examples.md
> +Based on your use specific cases, you may prefer to store your sensitive data with Basis Theory using our
```suggestion
Based on your use case, you may prefer to store your sensitive data with Basis Theory using our
```

2022-04-04 13:48 UTC, koalaty-code approved these changes

2022-04-04 13:53 UTC, merged