feat: deprecate atomic endpoints and remove atomic references
Basis-Theory/docs pull request #169
Opened 2022-04-08 00:55 UTC by jleon15

## Description
https://linear.app/basis-theory/issue/ENG-2687/deprecate-atomic-endpoints-in-api-docs

- Remove atomic cards section
- Remove atomic banks section
- Update deprecations section with atomic bank and card endpoints
- Update all references to atomic

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

<img width="1096" alt="Screen Shot 2022-04-07 at 18 51 45" src="https://user-images.githubusercontent.com/29789962/162342394-39524ed0-369b-462b-9d2d-53ce8040cfde.png">
<img width="1114" alt="Screen Shot 2022-04-07 at 18 52 18" src="https://user-images.githubusercontent.com/29789962/162342404-5836495f-7d67-431f-a32c-3a9ca8a7a424.png">
<img width="1147" alt="Screen Shot 2022-04-07 at 18 52 50" src="https://user-images.githubusercontent.com/29789962/162342408-6a25caa3-4aad-4065-8fc3-e57196cb9f16.png">
<img width="1165" alt="Screen Shot 2022-04-07 at 18 53 02" src="https://user-images.githubusercontent.com/29789962/162342413-49eedbd2-3a4b-460e-aca7-e1a78a3af768.png">

- [ ] Not Applicable

##
<img width="1786" alt="Screen Shot 2022-04-07 at 18 53 28" src="https://user-images.githubusercontent.com/29789962/162342417-ee4723be-e529-409f-a510-220a2d73a8e3.png">
 Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-04-08 12:43 UTC, bweber commented
@jleon15 Have we checked Guides to see if there is anything pointing to those atomic pages?

2022-04-08 13:58 UTC, jleon15 commented
> @jleon15 Have we checked Guides to see if there is anything pointing to those atomic pages?

There's a separate task for guides

2022-04-08 14:10 UTC, bweber commented
@jleon15 We won't be able to merge this until the guides PR is done also, so we release them at the same time.

2022-04-15 18:07 UTC, nloding commented on source/includes/api-reference/_tokens.md
> +| `routing_number` | true     | *string* | `null`  | Nine-digit ABA routing number         |
we should mention that we validate the checksum for the routing number also: https://en.wikipedia.org/wiki/ABA_routing_transit_number#Check_digit

2022-04-15 18:08 UTC, nloding commented on source/includes/api-reference/_tokens.md
> +| `routing_number` | true     | *string* | `null`  | Nine-digit ABA routing number         |
perhaps it should just link out to a description of the checksum and ABA requirements?

2022-04-20 13:08 UTC, djejaquino requested changes

2022-04-20 13:08 UTC, djejaquino commented on source/includes/elements/vanilla/_elements_services.md
>  In case any Elements service throws an error, that could be related to client-side validation or an unaccepted request from the server.
```suggestion
In case any Elements service throws an error, it could be related to client-side validation or an unaccepted request from the server.
```

2022-04-20 13:08 UTC, djejaquino commented on source/includes/elements/vanilla/_deprecations.md
> +| Service                     | Method | Deprecated      | Shutdown Date  | Details
The entire `Method` column can be removed.

2022-04-20 13:08 UTC, djejaquino commented on source/includes/elements/vanilla/_deprecations.md
> +| `storeCreditCard`   | BasisTheory.atomicBanks.create(CreateAtomicBank)      | December 10, 2021  | April 22, 2022  | `storeCreditCard` service will be removed in an upcoming release. Instead, pleas
```suggestion
| `storeCreditCard`   | BasisTheory.atomicBanks.create(CreateAtomicBank)      | December 10, 2021  | April 22, 2022  | `storeCreditCard` has been removed. Instead, please use [Tokens](#elements-services-tokens).                                                                                     | 
```

2022-04-20 18:15 UTC, djejaquino commented on source/includes/elements/vanilla/_elements_services.md
> +> Create Card token
This is not card

2022-04-20 20:27 UTC, djejaquino approved these changes

2022-04-20 20:55 UTC, djejaquino approved these changes

2022-04-20 20:55 UTC, bweber approved these changes

2022-04-20 20:56 UTC, merged

2022-04-20 20:57 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.34.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/docs/releases/tag/v1.34.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: