feat: Adding docs for search index and fingerprint expressions
Basis-Theory/docs pull request #183
Opened 2022-06-01 17:19 UTC by dhudec

## Description

- Consolidates all docs about expressions within the Expressions page on the docs
- Adds usage examples for search_indexes and fingerprint_expression

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/1900725/171464614-771d07fd-987d-4476-850a-781965240bd6.png)

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-06-01 18:17 UTC, dhudec commented on source/includes/expressions/_detokenization.md
> +<div></div>
These `div` separators are required to align code examples with the appropriate header, since  h3 elements (### in markdown) are not intended to be aligned to code samples

2022-06-01 21:01 UTC, koalaty-code requested changes

2022-06-02 17:10 UTC, koalaty-code approved these changes

2022-06-02 17:44 UTC, brigonzalez commented on source/includes/api-reference/_token-types.md
> +| **Default Fingerprint Expression** | <code>{{ data.account_number }}&#124;{{ data.routing_number }}</code>         |
had to do a few backflips here. using `code` tag because ``` don't allow `&#124;` to work, which is needed because markdown interprets `|` as a marker for the table

2022-06-02 17:48 UTC, koalaty-code approved these changes

2022-06-02 17:49 UTC, merged