feat: Documenting alias expressions and id input when creating tokens
Basis-Theory/docs pull request #207
Opened 2022-06-27 18:42 UTC by dhudec

## Description

NEED TO DOCUMENT SDK VERSIONS

- Documenting id input when creating a token
- Adds `Aliasing` section under `Expressions`
- Documents `alias_preserve_format` and `alias_preserve_length` filters

## Testing required outside of automated testing?

- [ ] Not Applicable

### Screenshots (if appropriate):

- [ ] Not Applicable

## Rollback / Rollforward Procedure

- [ ] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-06-27 18:46 UTC, dhudec commented on source/includes/expressions/_filters.md
> -## reveal_last
The diff is hard to read - but I alphabetized the filters so this one moved to the bottom.

2022-06-27 19:19 UTC, koalaty-code commented on source/includes/expressions/_aliasing.md
> +valuable for a generated token id to satisfy a specific format, or to allow a custom token id to be specified with
```suggestion
valuable for a generated token id to satisfy a specific format, or to allow a custom token id to be specified within
```

2022-06-27 19:19 UTC, koalaty-code commented on source/includes/expressions/_aliasing.md
> +there is not another token within your tenant with the same id. If a duplicate or invalid token id is found, a 400
We return a 409 CONFLICT response for a requested ID that results in a duplicate.

2022-06-27 19:19 UTC, koalaty-code commented on source/includes/expressions/_aliasing.md
> +  "type": "card",
```suggestion
  "type": "token",
```

2022-06-27 19:35 UTC, jleon15 reviewed
probably no screenshots because it is a draft but remember to add them please

2022-06-27 19:38 UTC, jleon15 commented on source/includes/api-reference/_tokens.md
> +| `id`                     | false    | *string*                                                | `null`                                    | A value or [expression](/expressions/#aliasing) specifyin
aren't UUID's random by definition? so saying `random UUID` is redundant

2022-06-27 20:13 UTC, dhudec commented on source/includes/expressions/_aliasing.md
> +  "type": "card",
This is technically ok, since we didn't restrict alias expressions to only tokens of type `token`.

2022-06-27 20:50 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +By default, when [creating a token](/#tokens-create-token), a random id (v4 UUID) will be generated to represent the
```suggestion
By default, when [creating a token](/#tokens-create-token), a random Id (v4 UUID) will be generated to represent the
```

2022-06-27 20:51 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +While randomly generated ids may be sufficient for many use cases, we have seen several scenarios in which it can be
```suggestion
While randomly generated Ids may be sufficient for many use cases, we have seen several scenarios in which it can be
```

2022-06-27 20:51 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +valuable for a generated token id to satisfy a specific format, or to allow a custom token id to be specified with
```suggestion
valuable for a generated token Id to satisfy a specific format, or to allow a custom token Id to be specified with
```

2022-06-27 20:51 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +- You would like the id to resemble the format of the underlying token data (e.g. to satisfy validation constraints)
```suggestion
- You would like the Id to resemble the format of the underlying token data (e.g. to satisfy validation constraints)
```

2022-06-27 20:52 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +- You wish to pre-generate token ids within your system
```suggestion
- You wish to pre-generate token Ids within your system
```

2022-06-27 20:53 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +- You wish to define your own custom algorithm for generating token ids
```suggestion
- You wish to define your own custom algorithm for generating token Ids
```

2022-06-27 20:53 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +2. Specifying how an id should be generated through the use of [Alias Expressions](#aliasing-alias-expressions)
```suggestion
2. Specifying how an Id should be generated through the use of [Alias Expressions](#aliasing-alias-expressions)
```

2022-06-27 20:53 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +A token id can be pre-generated by your system and provided when [creating a token](/#tokens-create-token)
```suggestion
A token Id can be pre-generated by your system and provided when [creating a token](/#tokens-create-token)
```

2022-06-27 20:54 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +within the `id` property. Any non-empty string value between 3 and 400 characters can be specified as an id, as long as
```suggestion
within the `id` property. Any non-empty string value between 3 and 400 characters can be specified as an Id, as long as
```

2022-06-27 20:55 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +there is not another token within your tenant with the same id. If a duplicate or invalid token id is found, a 400
```suggestion
there is not another token within your tenant with the same Id. If a duplicate or invalid token Id is found, a 400
```

2022-06-27 20:55 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +Alias expressions allow you to leverage the full [expression language](#language) to specify a token's id via a
```suggestion
Alias expressions allow you to leverage the full [expression language](#language) to specify a token's Id via a
```

2022-06-27 20:56 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +or [alias_preserve_length](#filters-alias_preserve_length)). These filters randomly generate a secure pseudonym based off the token's data.
```suggestion
or [alias_preserve_length](#filters-alias_preserve_length)). These filters randomly generate a secure pseudonym based on the token's data.
```

2022-06-27 21:08 UTC, jleon15 commented on source/includes/expressions/_intro.md
> +- [aliasing](#aliasing) when [creating a token](/api-reference/#tokens-create-token) or [tokenizing](/api-reference/#tokenize), to specify the id of the created token
```suggestion
- [aliasing](#aliasing) when [creating a token](/api-reference/#tokens-create-token) or [tokenizing](/api-reference/#tokenize), to specify the Id of the created token 
```

2022-06-27 21:09 UTC, jleon15 requested changes
added several comments

2022-06-29 15:08 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +Since token IDs are included within the URL route on some operations, some allowable special characters and whitespace
I don't understand this, did you forget to delete it?

2022-06-30 13:18 UTC, dhudec commented on source/includes/expressions/_aliasing.md
> +Since token IDs are included within the URL route on some operations, some allowable special characters and whitespace
No, this is accurate - I added this section on Limitations after your changes to restrict the set of allowable characters. There's a line right above what you highlighted that lists the restricted special characters, and this is saying that if you use any of them you'd get a 400 error back.

2022-06-30 16:12 UTC, jleon15 commented on source/includes/expressions/_aliasing.md
> +Since token IDs are included within the URL route on some operations, some allowable special characters and whitespace
I mean the URL encoding part

2022-06-30 16:38 UTC, jleon15 approved these changes

2022-06-30 17:43 UTC, merged

2022-06-30 17:45 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.55.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/docs/releases/tag/v1.55.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: