feat: add docs for elements reveal
Basis-Theory/docs pull request #239
Opened 2022-11-09 20:30 UTC by lcschy

## Description

- Adds documentation for detokenization using elements (`retrieve` and `setValue`)
- Adds documentation for static `value` prop

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

![Screen Shot 2022-11-09 at 17 26 14](https://user-images.githubusercontent.com/9054729/200935329-cac73e6a-057c-4ac3-809e-ea19fa5f7f0f.png)

![Screen Shot 2022-11-09 at 17 26 21](https://user-images.githubusercontent.com/9054729/200935363-15a6b5e6-0d26-400a-ac15-ea280c50e292.png)

![Screen Shot 2022-11-09 at 17 26 27](https://user-images.githubusercontent.com/9054729/200935370-ca409b2a-ae69-48fb-8d83-3f3c2efab109.png)

![Screen Shot 2022-11-09 at 17 26 37](https://user-images.githubusercontent.com/9054729/200935378-3c34f108-7d2f-44db-97b7-8f03f96be3fa.png)

- [ ] Not Applicable

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-11-14 13:33 UTC, djejaquino requested changes

2022-11-14 13:33 UTC, djejaquino commented on source/includes/elements/vanilla/_detokenization.md
> +> Retrieve generic token and set value into TextElement
```suggestion
> Retrieve `string` token data and set value into TextElement
```

2022-11-14 13:33 UTC, djejaquino commented on source/includes/elements/vanilla/_detokenization.md
> +    expiration_month: token.data.expiration_month,
```suggestion
    expiration_month: token.data.expiration_month, // expects number
```

2022-11-14 13:33 UTC, djejaquino commented on source/includes/elements/vanilla/_detokenization.md
> +method. When `retrieve` is called from Elements, the request is made from inside an Element `iframe`, hosted by Basis Theory.
```suggestion
method. When `retrieve` is called from a Basis Theory instance whereas `elements: true`, the API request is made from inside a Basis Theory hosted `iframe` and the returned data remains within it.
```

2022-11-14 13:33 UTC, djejaquino commented on source/includes/elements/vanilla/_element_methods.md
> +### Data Element Reference
I personally would not add any details about this element, since it is not directly useful; and reduces security through obscurity. 
Mentioning that the data is requested from it and stays within, should suffice.

2022-11-14 13:33 UTC, djejaquino commented on source/includes/elements/vanilla/_detokenization.md
> +  <span>Note that the <code>data</code> attribute in the token returned by the <code>retrieve</code> method is not the actual data, but a [reference](#data-element) to it.</span>
```suggestion
  <span>Note that the <code>data</code> attribute in the token returned by the <code>retrieve</code> method is a synthetic representation of the sensitive detokenized data.</span>
```

2022-11-14 14:22 UTC, djejaquino commented on source/includes/elements/vanilla/_detokenization.md
> +  if (error instanceof BasisTheoryValidationError) {
```suggestion
  if (error instanceof BasisTheoryApiError) {
```

2022-11-14 14:30 UTC, dhudec commented on source/includes/elements/vanilla/_detokenization.md
> +method. When `retrieve` is called from a Basis Theory instance whereas `elements: true`, the API request is made from inside a Basis Theory hosted `iframe` and the returned data remains within it.
```suggestion
method. When `retrieve` is called from a Basis Theory instance configured with `elements: true`, the API request is made from inside a Basis Theory hosted `iframe` and the returned data remains within it.
```

2022-11-14 14:47 UTC, djejaquino commented on source/includes/elements/vanilla/_element_methods.md
> +| `month`   | *number*       | [cardExpirationDate](#element-types-card-expiration-date-element) | Data-parsing method that resolves to the one-based month value of the input date.
Indexing.  `1` represents `January`.

2022-11-14 16:15 UTC, amkera commented on source/includes/elements/vanilla/_element_methods.md
> +| `month`   | *number*       | [cardExpirationDate](#element-types-card-expiration-date-element) | Data-parsing method that resolves to the one-based month value of the input date.
Can we say `one-indexed`? 
Or perhaps something like this:

```
Data-parsing method that resolves to the month value of the input date, where "January" = 1.
```

2022-11-14 18:59 UTC, djejaquino approved these changes

2022-11-14 19:05 UTC, dhudec approved these changes

2022-11-15 13:13 UTC, merged

2022-11-15 13:14 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.70.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/docs/releases/tag/v1.70.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: